### ISSUE TITLE
Table Scrolling Issue with navigation bar

### ISSUE THREAD

**Issue by SSGangwar** [jberlana/JBParallaxCell#11]
"JBParallaxCell"  is working fine with smooth scrolling if UIViewController does not have Navigation Bar, while if navigation bar is there on  UIViewController. In that case scrolling doesn't working fine and stuck a lot. Which does not looks good. I tried your sample code as well and when I embedded ViewController with Navigation Controller with Navigation Bar displayed, sample code also start stuck behavior while scrolling.  
Do you have an idea, why it happened, and how can we resolve this ?

**Comment by jberlana** [comment]
Try to set your navigation bar on the navigation controller opaque. I think the bad effect is caused by the blur transparent effect of the navigation bar, when I wrote this code this effect did not exists :(

**Comment by SSGangwar** [comment]
Thanks mate, it's working :+1:
