### ISSUE TITLE
Problem of segueing the view

### ISSUE THREAD

**Issue by Caldis** [jberlana/JBParallaxCell#5]
The JBParallaxCell are work very well in single view.
But if I use the JBParallaxCell for main view and segue into detailView, then return form  detailview to JBParallaxCell and it will reset the imageView position until you scroll the view.

**Comment by 8938948** [comment]
do you have something like this in your main view? If you have it will fix automatically, though I never had problems during pushing in view controllers.

-(void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [self scrollViewDidScroll:self.tableView];
}
